/** Influencer profil teklif kategorileri — ProfileHero / InfluencerProfileEditForm ile aynı sözlük. */
export const INFLUENCER_PROFILE_CATEGORY_TREE: Record<string, string[]> = {
  Moda: [
    'Günlük Kombin',
    'Streetwear',
    'Lüks Moda',
    'Tesettür Moda',
    'Ayakkabı',
    'Çanta & Aksesuar',
    'Takı',
    'Vintage Moda',
    'Erkek Modası',
    'Çocuk Modası',
  ],
  Güzellik: [
    'Makyaj',
    'Cilt Bakımı',
    'Saç Bakımı',
    'Erkek Bakımı',
    'Parfüm',
    'Estetik & Medikal Güzellik',
    'Nail Art',
    'Kozmetik Ürün İncelemesi',
  ],
  Teknoloji: [
    'Akıllı Telefon',
    'Bilgisayar Donanım',
    'Yazılım',
    'Yapay Zeka',
    'Siber Güvenlik',
    'Kripto & Blockchain',
    'Web3',
    'Gadget İncelemeleri',
    'Uygulama İncelemeleri',
    'SaaS Ürünleri',
  ],
  Oyun: [
    'PC Oyunları',
    'Konsol Oyunları',
    'Mobil Oyunlar',
    'E-Spor',
    'Twitch Yayıncılığı',
    'Oyun İnceleme',
    'Retro Oyun',
  ],
  Yemek: [
    'Restoran İnceleme',
    'Ev Yemekleri',
    'Tatlı',
    'Vegan Beslenme',
    'Diyet Tarifler',
    'Sokak Lezzetleri',
    'Kahve Kültürü',
    'Dünya Mutfağı',
  ],
  Seyahat: [
    'Yurt İçi',
    'Yurt Dışı',
    'Lüks Tatil',
    'Kamp & Karavan',
    'Kültür Turları',
    'Backpacking',
    'Otel İnceleme',
    'Uçuş & Havayolu Deneyimi',
  ],
  Fitness: [
    'Vücut Geliştirme',
    'Crossfit',
    'Yoga',
    'Pilates',
    'Koşu',
    'Diyet & Beslenme',
    'Supplement',
    'Evde Spor',
  ],
  'Yaşam Tarzı': [
    'Günlük Vlog',
    'Minimalizm',
    'Ev Dekorasyon',
    'Kişisel Gelişim',
    'Sabah Rutinleri',
    'Üretkenlik',
    'Sürdürülebilir Yaşam',
  ],
  Eğitim: [
    'YKS',
    'KPSS',
    'Dil Öğrenimi',
    'Yurtdışı Eğitim',
    'Yazılım Eğitimi',
    'Akademik İçerik',
    'Çocuk Eğitimi',
    'Kariyer Tavsiyeleri',
  ],
  Eğlence: [
    'Mizah',
    'Skeç',
    'Challenge',
    'Prank',
    'Trend İçerikler',
    'Talk Show',
    'Sokak Röportajı',
  ],
  'Finans & Yatırım': [
    'Borsa',
    'Kripto',
    'Forex',
    'Kişisel Finans',
    'Girişimcilik',
    'E-Ticaret',
    'Pasif Gelir',
    'Startup',
  ],
  Otomotiv: [
    'Araç İnceleme',
    'Elektrikli Araç',
    'Modifiye',
    'Motor',
    'Araç Aksesuar',
    'Test Sürüşü',
  ],
  'Medya & Sanat': [
    'Sinema',
    'Dizi İnceleme',
    'Müzik',
    'Podcast',
    'Kitap',
    'Fotoğrafçılık',
    'Drone Çekimi',
    'Grafik Tasarım',
  ],
  'Anne & Çocuk': [
    'Hamilelik',
    'Bebek Ürünleri',
    'Çocuk Gelişimi',
    'Oyuncak İnceleme',
    'Aile Vlog',
  ],
  'Evcil Hayvanlar': [
    'Köpek',
    'Kedi',
    'Egzotik Hayvan',
    'Mama İnceleme',
    'Eğitim',
  ],
  'Psikoloji & Mental Sağlık': [
    'İlişkiler',
    'Motivasyon',
    'Mindfulness',
    'Terapi Deneyimleri',
    'Öz Güven',
  ],
  'Niş & Özel Alanlar': [
    'Saat & Lüks Aksesuar',
    'Koleksiyon',
    'ASMR',
    'Mukbang',
    'Tarot & Astroloji',
    'Sokak Modası Röportaj',
  ],
  'Spor (Detaylandırılmış)': [
    'Futbol',
    'Basketbol',
    'Voleybol',
    'MMA',
    'Tenis',
    'Motor Sporları',
  ],
};

export const INFLUENCER_PROFILE_TOP_CATEGORIES = Object.keys(INFLUENCER_PROFILE_CATEGORY_TREE);
