/**
 * Influencer üst/alt kategori ağacı — marka kayıt sektörleri ile paylaşılır.
 * Güncel liste + önceki ağaçtan (çakışmayan) ek alt maddeler.
 */
export const CATEGORY_TREE: Record<string, string[]> = {
  "Moda & Giyim": [
    "Kadın Giyim",
    "Erkek Giyim",
    "Spor Giyim",
    "Streetwear",
    "Tesettür Moda",
    "Ayakkabı",
    "Çanta & Aksesuar",
    "Takı & Mücevher",
    "Günlük Kombin",
    "Vintage Moda",
    "Çocuk Giyim",
  ],
  "Güzellik & Kozmetik": [
    "Makyaj",
    "Cilt Bakımı",
    "Saç Bakımı",
    "Parfüm",
    "Erkek Bakım",
    "Dermokozmetik",
    "Estetik & Klinik",
    "Nail Art",
    "Kozmetik Ürün İncelemesi",
    "Estetik & Medikal Güzellik",
  ],
  "Sağlık & Wellness": [
    "Takviye Gıda",
    "Vitamin & Mineral",
    "Mental Sağlık",
    "Meditasyon & Yoga",
    "Diyet & Beslenme",
    "Klinik Hizmetler",
    "İlişkiler",
    "Motivasyon",
    "Mindfulness",
    "Terapi Deneyimleri",
    "Öz Güven",
  ],
  "Spor & Fitness": [
    "Fitness",
    "Crossfit",
    "Yoga & Pilates",
    "Spor Ekipmanları",
    "Outdoor Sporlar",
    "Kişisel Antrenörlük",
    "Vücut Geliştirme",
    "Koşu",
    "Evde Spor",
    "Futbol",
    "Basketbol",
    "Voleybol",
    "MMA",
    "Tenis",
    "Motor Sporları",
  ],
  Teknoloji: [
    "Tüketici Elektroniği",
    "Yazılım & SaaS",
    "Mobil Uygulamalar",
    "Yapay Zeka",
    "Blockchain",
    "Donanım",
    "Akıllı Telefon",
    "Bilgisayar Donanım",
    "Siber Güvenlik",
    "Web3",
    "Gadget İncelemeleri",
    "Uygulama İncelemeleri",
    "Kripto & Blockchain",
  ],
  Gaming: [
    "PC Gaming",
    "Mobil Oyun",
    "Konsol",
    "E-spor",
    "Yayıncılık (Twitch / Kick)",
    "PC Oyunları",
    "Konsol Oyunları",
    "Mobil Oyunlar",
    "Oyun İnceleme",
    "Retro Oyun",
  ],
  Eğitim: [
    "Online Eğitim",
    "Dil Eğitimi",
    "Üniversite / Akademik",
    "Kişisel Gelişim",
    "Sertifika Programları",
    "YKS",
    "KPSS",
    "Dil Öğrenimi",
    "Yurtdışı Eğitim",
    "Yazılım Eğitimi",
    "Akademik İçerik",
    "Çocuk Eğitimi",
    "Kariyer Tavsiyeleri",
  ],
  "Finans & Fintech": [
    "Bankacılık",
    "Yatırım",
    "Kripto",
    "Sigorta",
    "Ödeme Sistemleri",
    "Borsa",
    "Forex",
    "Kişisel Finans",
    "Girişimcilik",
    "E-Ticaret",
    "Pasif Gelir",
    "Startup",
  ],
  "E-ticaret & Perakende": [
    "Marketplace",
    "D2C Markalar",
    "Dropshipping",
    "Abonelik Modelleri",
  ],
  "Yemek & İçecek": [
    "Restoran",
    "Kafe",
    "Fast Food",
    "Sağlıklı Beslenme",
    "Gıda Ürünleri",
    "İçecek Markaları",
    "Restoran İnceleme",
    "Ev Yemekleri",
    "Tatlı",
    "Vegan Beslenme",
    "Sokak Lezzetleri",
    "Kahve Kültürü",
    "Dünya Mutfağı",
  ],
  "Seyahat & Turizm": [
    "Oteller",
    "Tatil Paketleri",
    "Havayolu",
    "Tur Operatörleri",
    "Airbnb / Kiralama",
    "Yurt İçi",
    "Yurt Dışı",
    "Lüks Tatil",
    "Kamp & Karavan",
    "Kültür Turları",
    "Backpacking",
    "Otel İnceleme",
    "Uçuş & Havayolu Deneyimi",
  ],
  Otomotiv: [
    "Araç Satışı",
    "Araç Kiralama",
    "Elektrikli Araçlar",
    "Aksesuar & Parça",
    "Araç İnceleme",
    "Modifiye",
    "Motor",
    "Test Sürüşü",
  ],
  "Ev & Yaşam": [
    "Mobilya",
    "Dekorasyon",
    "Ev Tekstili",
    "Mutfak Ürünleri",
    "Günlük Vlog",
    "Minimalizm",
    "Ev Dekorasyon",
    "Sabah Rutinleri",
    "Üretkenlik",
    "Sürdürülebilir Yaşam",
  ],
  "Anne & Bebek": [
    "Bebek Ürünleri",
    "Oyuncak",
    "Eğitim",
    "Hamilelik Ürünleri",
    "Hamilelik",
    "Çocuk Gelişimi",
    "Oyuncak İnceleme",
    "Aile Vlog",
  ],
  "Evcil Hayvanlar": [
    "Mama",
    "Aksesuar",
    "Veteriner Hizmetleri",
    "Köpek",
    "Kedi",
    "Egzotik Hayvan",
    "Mama İnceleme",
    "Pet Eğitimi",
  ],
  "Eğlence & Medya": [
    "Film & Dizi",
    "Müzik",
    "İçerik Platformları",
    "Etkinlik & Organizasyon",
    "Mizah",
    "Skeç",
    "Challenge",
    "Prank",
    "Trend İçerikler",
    "Talk Show",
    "Sokak Röportajı",
    "Sinema",
    "Dizi İnceleme",
    "Podcast",
    "Kitap",
    "Fotoğrafçılık",
    "Drone Çekimi",
    "Grafik Tasarım",
    "ASMR",
    "Mukbang",
    "Tarot & Astroloji",
    "Sokak Modası Röportaj",
  ],
  "Kurumsal & B2B": [
    "Yazılım Hizmetleri",
    "Ajanslar",
    "Danışmanlık",
    "HR & İşe Alım",
  ],
  Gayrimenkul: [
    "Konut",
    "Ticari Gayrimenkul",
    "Proje Geliştirme",
  ],
  "Lüks & Premium": [
    "Lüks Moda",
    "Saat",
    "Mücevher",
    "Premium Hizmetler",
    "Koleksiyon",
    "Saat & Lüks Aksesuar",
  ],
  "Sosyal Sorumluluk": [
    "STK",
    "Kampanyalar",
    "Bağış Platformları",
  ],
};

export const TOP_CATEGORY_KEYS = Object.keys(CATEGORY_TREE);

/** Kayıtta kullanılan tüm alt kategoriler (marka/influencer seçim ağacı — tekilleştirilmiş, TR sıralı) */
export const ALL_REGISTRATION_SUBCATEGORIES: string[] = (() => {
  const set = new Set<string>();
  for (const subs of Object.values(CATEGORY_TREE)) {
    subs.forEach((s) => set.add(s));
  }
  return Array.from(set).sort((a, b) => a.localeCompare(b, 'tr'));
})();
